create table book (
    id bigint generated by default as identity primary key
);

create table book_copy (
    book_id bigint,
    copy_number int
);

create table book_copy_quality_control (
    book_id bigint,
    copy_number int, -- renamed key column of Book.copies
    book_copy_key int, -- default named key column of Book.copies.qualityControls
    quality_control_number int
);
