CREATE TABLE MAIN_ENTITIES (
    ID INTEGER IDENTITY PRIMARY KEY,
    ANOTHER_ID VARCHAR (200) NOT NULL
);

CREATE TABLE SECOND_ENTITIES (
    ID INTEGER IDENTITY PRIMARY KEY,
    MAIN_ENTITY_ID INTEGER REFERENCES MAIN_ENTITIES(ID)
);