create table book (
    id bigint generated by default as identity primary key
);

create table book_copy (
    book_id bigint,
    copy_number int
);

create table book_copy_quality_control (
    book_id bigint not null,
    copy_number int not null,
    quality_control_number int
);
