CREATE TABLE STUDENT
(
    STUDENT_ID   INTEGER IDENTITY PRIMARY KEY,
    STUDENT_NAME VARCHAR(200) NOT NULL
);

CREATE TABLE STUDENT_COURSE
(
    STUDENT_ID INTEGER,
    COURSE_ID  integer NOT NULL,
    PRIMARY KEY (STUDENT_ID, COURSE_ID)
);

CREATE TABLE COURSE
(
    COURSE_ID   INTEGER IDENTITY PRIMARY KEY,
    COURSE_NAME VARCHAR(200) NOT NULL
);

CREATE TABLE TEST_SCORE
(
    COURSE_REF INTEGER,
    INDEX INTEGER IDENTITY PRIMARY KEY,
    VALUE            INTEGER
);