CREATE TABLE COURSE
(
    COURSE_ID   INTEGER IDENTITY PRIMARY KEY,
    COURSE_NAME VARCHAR(200) NOT NULL
);

CREATE TABLE STUDENT
(
    STUDENT_ID   INTEGER IDENTITY PRIMARY KEY,
    STUDENT_NAME VARCHAR(200) NOT NULL
);

CREATE TABLE STUDENT_COURSE
(
    ID INTEGER IDENTITY PRIMARY KEY,
    STUDENT_ID INTEGER NOT NULL,
    COURSE_ID  INTEGER NOT NULL,
    UNIQUE (STUDENT_ID, COURSE_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
);

CREATE TABLE TEST_SCORE
(
    COURSE_REF INTEGER,
    INDEX INTEGER,
    VALUE            INTEGER,
    PRIMARY KEY (COURSE_REF, INDEX),
    FOREIGN KEY (COURSE_REF) REFERENCES STUDENT_COURSE(ID)
);