CREATE TABLE RECORD_ENTITY
(
    ID IDENTITY NOT NULL PRIMARY KEY,
    NAME       VARCHAR(100),
    CREATED_AT TIMESTAMP
);

CREATE TABLE CLASS_ENTITY
(
    ID IDENTITY NOT NULL PRIMARY KEY,
    NAME       VARCHAR(100),
    CREATED_AT TIMESTAMP
);