CREATE TABLE ASYNC_TASK (
    ID INTEGER IDENTITY PRIMARY KEY,
    NAME VARCHAR (200) NOT NULL
);

CREATE TABLE  DEPENDENT_TASK (
    ASYNC_TASK INTEGER NOT NULL REFERENCES ASYNC_TASK(ID),
    ID INTEGER NOT NULL REFERENCES ASYNC_TASK(ID)
);