CREATE TABLE ASYNC_TASK (
    ID INTEGER IDENTITY PRIMARY KEY,
    NAME VARCHAR (200) NOT NULL
);

CREATE TABLE  DEPENDENT_TASK (
    FROM_ID INTEGER NOT NULL REFERENCES ASYNC_TASK(ID),
    TO_ID INTEGER NOT NULL REFERENCES ASYNC_TASK(ID)
);